### ISSUE TITLE
SUM or COUNT in hql?

### ISSUE THREAD

**Issue by fslzdd** [hadooparchitecturebook/hadoop-arch-book#1]
In ch09-clickstream/HiveSessionize/04-query-parquet-log-table.hql:

Is it assumed to be as below?

SELECT (SUM(CASE WHEN count!=1 THEN 0 ELSE 1 END))_100/(__COUNT__(count)) bounce_rate FROM (SELECT session_id, COUNT(_) count FROM apache_log_parquet GROUP BY session_id)t;

**Comment by markgrover** [comment]
That's an excellent observation. We were trying to find the percentage of clicks that were 'bouncing'. However, re-reading the definition on [wikipedia](http://en.wikipedia.org/wiki/Bounce_rate), it seems like the correct denominator should be the total number of sessions in the day and not the total number of clicks in the day. So, any of COUNT(count), count(*) or count(session_id) would work. We'll update. Thank you for notifying!
